name: location_platform_interface
description: A common platform interface for the location plugin.
version: 5.0.0
homepage: https://github.com/Lyokone/flutterlocation

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  async: ^2.11.0
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
#  leancode_lint: ^13.0.0
  mockito: ^5.4.4
